name: Publish Release

on:
  push:
    tags:
      - 'v*.*' # Trigger the workflow on tag creation with the format "vX.Y"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller nltk joblib scikit-learn

    - name: Build EXE
      run: |
        # Get the version number from the tag (e.g., v1.0.0)
        $env:VERSION = $env:GITHUB_REF -replace '^refs/tags/v', ''
        
        # Run PyInstaller with custom name and version
        pyinstaller --onefile try_model.py -n is-this-bible.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}

    - name: Create Artifact Directory
      run: mkdir -p artifacts
      
    - name: Copy Output File to Artifact Directory
      run: copy dist\is-this-bible.exe artifacts\ 

    - name: Prepare Additional Files
      run: |
        copy is_this_bible_model.pkl artifacts\
        copy is_this_bible_vectorizer.pkl artifacts\

    - name: Zip Artifact Directory
      run: |
        cd artifacts
        powershell -Command "Compress-Archive -Path * -DestinationPath is-this-bible.zip"
        


    - name: Set version number
      run: |
        # Get the version number from the tag (e.g., v1.0.0)
        $env:VERSION = $env:GITHUB_REF -replace '^refs/tags/v', ''
        echo $env:VERSION > version.txt # Update version.txt with your desired version

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: "artifacts/is-this-bible.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
